#!/usr/bin/env node
/* ==========================================================================
   fetch-faqs.js — pull FAQ categories and entries from Contentful and write
   assets/data/faqs-content.html, a static HTML fragment. build.js then
   inlines that fragment into faqs.html between the
   <!-- @cms:faqs start/end --> markers, the same way it inlines the shared
   header/footer partials.

   Content model (create these in Contentful before running):

     faqCategory
       title   Symbol   required
       order   Integer  required

     faqEntry
       question   Symbol     required
       answer     RichText   required
       category   Reference -> faqCategory, required
       order      Integer    required

   Requires CONTENTFUL_SPACE_ID and CONTENTFUL_DELIVERY_TOKEN in the
   environment. If they are not set, this script does nothing and exits
   cleanly — the fragment file (and the hardcoded content already in
   faqs.html) is left untouched, so the site keeps working as-is until
   Contentful is configured.

   Run: node scripts/fetch-faqs.js
   ========================================================================== */
const fs = require("fs");
const path = require("path");
const { isConfigured, fetchAllEntries } = require("./lib/contentful");
const { renderRichText } = require("./lib/rich-text-html");

const OUT_FILE = path.join(__dirname, "..", "assets", "data", "faqs-content.html");

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

async function main() {
  if (!isConfigured()) {
    console.log("Contentful not configured (CONTENTFUL_SPACE_ID / CONTENTFUL_DELIVERY_TOKEN missing) — skipping FAQ fetch.");
    return;
  }

  const [categories, faqEntries] = await Promise.all([
    fetchAllEntries("faqCategory", { order: "fields.order" }),
    fetchAllEntries("faqEntry", { order: "fields.order" }),
  ]);

  const entriesByCategory = new Map();
  for (const entry of faqEntries) {
    const categoryId = entry.fields.category?.sys?.id;
    if (!categoryId) continue;
    if (!entriesByCategory.has(categoryId)) entriesByCategory.set(categoryId, []);
    entriesByCategory.get(categoryId).push(entry);
  }

  const sections = categories
    .filter((c) => entriesByCategory.has(c.id))
    .map((category) => {
      const items = entriesByCategory
        .get(category.id)
        .map(
          (entry) => `        <details>
          <summary>${escapeHtml(entry.fields.question)}</summary>
          <div class="faq-body">
            ${renderRichText(entry.fields.answer)}
          </div>
        </details>`
        )
        .join("\n");
      return `      <h2>${escapeHtml(category.fields.title)}</h2>
      <div class="faq">
${items}
      </div>`;
    })
    .join("\n\n");

  const out =
    "<!-- Generated by scripts/fetch-faqs.js from Contentful — do not edit by hand. -->\n" +
    sections +
    "\n";

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, out, "utf8");
  console.log(`Wrote ${categories.length} FAQ categories (${faqEntries.length} questions) to ${path.relative(process.cwd(), OUT_FILE)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
